def get_games
  return [
{
"id": 1,
"name": "Root",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1540147295104",
"price": 45,
"max_players": 4,
"min_players": 2,
"play_time": 60,
"description": "Find adventure in this marvelous asymmetric game. Root provides limitless replay value as you and your friends explore the unique factions all wanting to rule a fantastic forest kingdom. Play as the Marquise de Cat and dominate the woods, extracting its riches and policing its inhabitants, as the Woodland Alliance, gathering supporters and coordinate revolts against the ruling regime, the Eyrie Dynasties, regaining control of the woods while keeping your squabbling court at bay, or as the Vagabond, seeking fame and fortune as you forge alliances and rivalries with the other players. Each faction has its own play style and paths to victory, providing an immersive game experience you will want to play again and again.",
"genre": "Fantasy",
"rating": 3.9703688618486384,
"rank": 1,
"board_score": 5,
"card_score": 1,
"party_score": 7,
"players_score": 4
},
{
"id": 2,
"name": "Gloomhaven",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254920151-51ulRXlJ7LL.jpg",
"price": 109.95,
"max_players": 4,
"min_players": 1,
"play_time": 60,
"description": "Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world. Players must work together out of necessity to clear out menacing dungeons and forgotten ruins. In the process they will enhance their abilities with experience and loot, discover new locations to explore and plunder, and expand an ever-branching story fueled by the decisions they make. This is a legacy game with a persistent and changing world that is ideally played over many game sessions. After a scenario, players will make decisions on what to do, which will determine how the story continues, kind of like a &quot;Choose Your Own Adventure&quot; book. Playing through a scenario is a cooperative affair where players will fight against automated monsters using an innovative card system to determine the order of play and what a player does on their turn.",
"genre": "Fantasy",
"rating": 4.171210954420754,
"rank": 2,
"board_score": 3,
"card_score": 1,
"party_score": 10,
"players_score": 3

},
{
"id": 3,
"name": "Scythe",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254971843-513-lrmjs2L.jpg",
"price": 59.15,
"max_players": 5,
"min_players": 1,
"play_time": 90,
"description": "Scythe gives players almost complete control over their fate. Other than each player's individual hidden objective card, the only elements of luck or variability are &quot;Encounter&quot; cards that players will draw as they interact with the citizens of newly explored lands. Each encounter card provides the player with several options, allowing them to mitigate the luck of the draw through their selection. Combat is also driven by choices, not luck or randomness. <br /Scythe uses a streamlined action-selection mechanism (no rounds or phases) to keep gameplay moving at a brisk pace and reduce downtime between turns. While there is plenty of direct conflict for players who seek it, there is no player elimination. Every part of Scythe has an aspect of engine-building to it. Players can upgrade actions to become more efficient, build structures that improve their position on the map, enlist new recruits to enhance character abilities, activate mechs to deter opponents from invading, and expand their borders to reap greater types and quantities of resources. These engine-building aspects create a sense of momentum and progress throughout the game. The order in which players improve their engine adds to the unique feel of each game, even when playing one faction multiple times.",
"genre": "Sci-Fi",
"rating": 3.962750960165058,
"rank": 3,
"board_score": 7,
"card_score": 1,
"party_score": 4,
"players_score": 4
},
{
"id": 4,
"name": "Wingspan",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1545152463996",
"price": 47.99,
"max_players": 5,
"min_players": 1,
"play_time": 40,
"description": "Wingspan is a competitive, medium-weight, card-driven, engine-building board game from Stonemaier Games. You are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your aviary. Each bird extends a chain of powerful combinations in one of your habitats (actions). These habitats focus on several key aspects of growth:   Gain food tokens via custom dice in a birdfeeder dice tower</Lay eggs using egg miniatures in a variety of colors Draw from hundreds of unique bird cards and play them. The winner is the player with the most points after 4 rounds.",
"genre": "Card Game",
"rating": 3.9680781250000003,
"rank": 4,
"board_score": 1,
"card_score": 8,
"party_score": 2,
"players_score": 3
},
{
"id": 5,
"name": "Terraforming Mars",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254934477-61ys4u7ejfL.jpg",
"price": 41.99,
"max_players": 5,
"min_players": 3,
"play_time": 90,
"description": "In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level and the ocean coverage until the environment is habitable. In Terraforming Mars you play one of those corporations and work together in the terraforming process, but compete in doing the best work, with victory points awarded not only for your contribution to the terraforming, but also for advancing human infrastructure throughout the solar systems and other commendable achievements. The players acquire unique project cards, which represent anything from introducing plant life or animals, hurling asteroids at the surface, building cities, and establishing greenhouse gas industries to heat up the atmosphere. You compete for the best places for your city tiles, ocean tiles and greenery tiles. When the terraforming process is complete, the player corporation with the most victory points wins.",
"genre": "Sci-Fi",
"rating": 3.8687349936296775,
"rank": 5,
"board_score": 5,
"card_score": 1,
"party_score": 5,
"players_score": 3
},
{
"id": 6,
"name": "Azul",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200327-61EFZADvURL.jpg",
"price": 27.47,
"max_players": 4,
"min_players": 2,
"play_time": 30,
"description": "Azul was designed by the world famous, award-winning game author Michael Riesling. Azul captures the beautiful aesthetics of Moorish art in a contemporary board game. Players compete as artisans decorating the walls of the royal Palace of Dvora. By carefully drafting the correct Quantity and style of tiles, the most clever of artisans plan ahead to maximize the beauty of their work (not to mention their scores!) while ensuring they wasted no supplies in the process. Introduced by the moors, &quot;azulejos&quot; (originally white and blue ceramic tiles) were fully embraced by the Portuguese, when their King Manuel I, on a visit to the Alhambra Palace in Southern Spain, was mesmerized by the stunning beauty of the Moorish decorative tiles. The King, awestruck by the interior beauty of the Alhambra, immediately ordered that his own Palace in Portugal be decorated with similar wall tiles. As a tile-laying artist, you have been challenged to embellish the walls of the royal Palace of Dvora.",
"genre": "Strategy",
"rating": 3.7552308802308794,
"rank": 6,
"board_score": 1,
"card_score": 1,
"party_score": -6,
"players_score": 2
},
{
"id": 7,
"name": "Viticulture: Essential Edition",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254894908-61llEAverzL.jpg",
"price": 44.5,
"max_players": 6,
"min_players": 1,
"play_time": 90,
"description": "Viticulture is a worker-placement game set in the foothills of Tuscany. The Essential Edition includes the second edition of Viticulture along with several elements from the original Tuscany expansion pack, hand-picked by famed designer Uwe Rosenberg.",
"genre": "Economic",
"rating": 3.9033377215706606,
"rank": 7,
"board_score": 5,
"card_score": 7,
"party_score": 0,
"players_score": 5
},
{
"id": 85,
"name": "Food Chain Magnate",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1577924173686",
"price": 89.97,
"max_players": 5,
"min_players": 2,
"play_time": 120,
"description": " Food Chain Magnate is a heavy strategy game about building a fast food chain. The focus is on building your company using a card-driven (human) resource management system. Players compete on a variable city map through purchasing, marketing and sales, and on a job market for key staff members.",
"genre": "Econonmic",
"rating": 3.9638370765131343,
"rank": 8,
"board_score": 1,
"card_score": 8,
"party_score": 2,
"players_score": 5
},
{
"id": 8,
"name": "Spirit Island",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254941010-61PJxjjnbfL.jpg",
"price": 54.99,
"max_players": 4,
"min_players": 1,
"play_time": 90,
"description": "Powerful Spirits have existed on this isolated island for time immemorial. They are both part of the natural world and - at the same time - something beyond nature. Native Islanders, known as the Dahan, have learned how to co-exist with the spirits, but with a healthy dose of fear and reverence. However, now, the island has been &quot;discovered&quot; by invaders from a far-off land. These would-be colonists are taking over the land and upsetting the natural balance, destroying the presence of Spirits as they go. As Spirits, you must grow in power and work together to drive the invaders from your island... before it's too late!",
"genre": "Fantasy",
"rating": 3.934680293148659,
"rank": 8,
"board_score": 6,
"card_score": 1,
"party_score": 7,
"players_score": 4
},
{
"id": 9,
"name": "Pandemic",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254186140-51iNoyxoamL.jpg",
"price": 17.49,
"max_players": 4,
"min_players": 2,
"play_time": 45,
"description": "After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants &amp; Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you!   <h4>Artists:</h4> Joshua Cappel (graphics and illustration) Régis Moulun (cover painting) Chris Quilliams (2013 edition)",
"genre": "Strategy",
"rating": 3.535555596401839,
"rank": 9,
"board_score": 8,
"card_score": 8,
"party_score": 3,
"players_score": 4
},
{
"id": 10,
"name": "Codenames",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
"price": 13.49,
"max_players": 8,
"min_players": 2,
"play_time": 15,
"description": "The two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES. The teams compete to see who can make contact with all of their agents first. Spymasters give one-word clues that can point to multiple words on the board. Their teammates try to guess words of the right color while avoiding those that belong to the opposing team. And everyone wants to avoid the assassin. Codenames: win or lose, it's fun to figure out the clues.",
"genre": "Party Game",
"rating": 3.577229547342195,
"rank": 10,
"board_score": 0,
"card_score": 7,
"party_score": 9,
"players_score": 8
},
{
"id": 11,
"name": "7 Wonders",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
"price": 29.12,
"max_players": 7,
"min_players": 2,
"play_time": 30,
"description": "You are the leader of one of the 7 great cities of the Ancient World. Gather resources, develop commercial routes and affirm your military supremacy. Build your city and erect an architectural wonder which will transcend future times! 7 Wonders is a simple and addictive game for the whole family. In 30 minutes you can raise a complete civilization and build the greatest Wonders of the World.Winner of the 2011 Kennerspiel des Jahres (Enthusiasts Game of the Year) Award.",
"genre": "Card Game",
"rating": 3.574596273291928,
"rank": 11,
"board_score": 2,
"card_score": 9,
"party_score": 1,
"players_score": 6
},
{
"id": 12,
"name": "7 Wonders Duel",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559255812092-51S3zQnsPBL.jpg",
"price": 24.99,
"max_players": 2,
"min_players": 2,
"play_time": 30,
"description": " 7 Wonders Duel is a fast-paced, two-player edition of Antoine Bauza's award-winning civilization-building game.",
"genre": "Card Game",
"rating": 3.8029949372082323,
"rank": 12,
"board_score": -2,
"card_score": 1,
"party_score": -2,
"players_score": 2
},
{
"id": 13,
"name": "Carcassonne",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254282618-61HduAZGE7L.jpg",
"price": 28.94,
"max_players": 5,
"min_players": 2,
"play_time": 30,
"description": "Each game of <em>Carcassonne</em> reveals a unique environment as tiles form a landscape of cities, roads, fields, and monasteries. Claim these features with your followers to win the game. <em>Carcassonne</em> is a tile placement game where players collectively construct the area around the medieval French city of Carcassonne while competing to place followers on various features and score the most points. First published in 2000, the game's accessible yet deep design has attracted a wide fan base and led to the development of numerous expansions (eg Rivers) and standalone titles in the <em>Carcassonne</em> line.",
"genre": "Territory Building",
"rating": 3.4673366834170887,
"rank": 13,
"board_score": 6,
"card_score": 1,
"party_score": 1,
"players_score": 4
},
{
"id": 14,
"name": "The Castles of Burgundy",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254202422-51mP2aJfyxL.jpg",
"price": 31.95,
"max_players": 4,
"min_players": 2,
"play_time": 30,
"description": "15th century princes from the Loire Valley devote their efforts to strategic trading and building in order to bring their estates to prosperity and prominence. Over the course of 5 rounds, collect the most points by trading, live stock farming, city building and scientific research to win! The Hundred Years? war is over and the Renaissance is looming. Conditions are perfect for the princes of the Loire Valley to propel their estates to prosperity and prominence. Through strategic trading and building, clever planning, and careful thought, players add settlements and castles, practice trade along the river, exploit silver mines, farm livestock, and more in this classic Stefan Feld Eurogame. How to Play: 1. Players take turns rolling two dice and choosing to move goods tiles from the game board to their player boards; from their player boards onto corresponding numbered and colored regions of their playing fields; to deliver goods in exchange for silverlings; or to take worker tiles. 2. Play continues, with players completing additional actions and noting victory points for each tile placed. 3. Five turns are taken per round, with additional victory points awarded for unused money and workers, undelivered goods, and percentage of settlement complete. The player with the most victory points after five rounds wins the game.",
"genre": "Territory Building",
"rating": 3.890122704264174,
"rank": 14,
"board_score": 6,
"card_score": 1,
"party_score": 2,
"players_score": 3
},
{
"id": 15,
"name": "Pandemic Legacy: Season 1",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257833516-612BUfjuA7fL.jpg",
"price": 62.99,
"max_players": 4,
"min_players": 2,
"play_time": 60,
"description": "The world is on the brink of disaster. In Pandemic Legacy, your disease-fighting team must keep four deadly diseases at bay for a whole year. Each month will bring new surprises, and your actions in each game will have repercussions on the next. Will you let cities fall to the diseases? Will your team be enough to keep the viruses at bay for a whole year? Craft your own unique Pandemic experience with Pandemic Legacy.",
"genre": "Strategy",
"rating": 4.166694448362551,
"rank": 15,
"board_score": 7,
"card_score": 8,
"party_score": 3,
"players_score": 4
},
{
"id": 16,
"name": "Concordia",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1538065470418",
"price": 61.81,
"max_players": 5,
"min_players": 2,
"play_time": 90,
"description": "2,000 years ago, the Roman Empire ruled the lands around the Mediterranean Sea. With peace at the borders, harmony inside the provinces, uniform law, and a common currency, the economy thrived and gave rise to mighty Roman dynasties as they expanded throughout the numerous cities. Guide one of these dynasties and send colonists to the remote realms of the Empire, develop your trade network, and appease the ancient gods to curry their favor - all to gain the chance to emerge victorious in Concordia.",
"genre": "Economic",
"rating": 4.017421602787456,
"rank": 16,
"board_score": 1,
"card_score": 1,
"party_score": -4,
"players_score": 4
},
{
"id": 36,
"name": "Clank! A Deck-Building Adventure",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254970101-61gHdS3ds2L.jpg",
"price": 40.5,
"max_players": 4,
"min_players": 2,
"play_time": 30,
"description": "Burgle your way to adventure in Clank!, the new deck-building board game. Sneak into an angry dragon's mountain lair to steal precious artifacts. Delve deeper to find more valuable loot. Acquire cards for your deck and watch your thievish abilities grow. Be quick and be quiet. One false-step and --CLANK! Each careless sound draws the attention of the dragon, and each artifact stolen increases its rage. You can only enjoy your plunder if you make it out of the depths alive!",
"genre": "Fantasy",
"rating": 3.6863139735480157,
"rank": 36,
"board_score": 2,
"card_score": 1,
"party_score": 9,
"players_score": 3
},
{
"id": 17,
"name": "Splendor",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254164722-51AHDwGznvL.jpg",
"price": 29.99,
"max_players": 4,
"min_players": 2,
"play_time": 30,
"description": "As a wealthy Renaissance merchant, acquire mines and transportation, hire artisans and woo the nobility. Create the most fantastic jewelry to become the best-known merchant of them all! Acquire precious stones to trade them for development cards. Use development cards to acquire more gem stones. Use your gems and gold to create the most fantastic jewelry, and appeal to the nobles to gain the prestige you need to win.Splendor is a fast-paced and addictive game of chip-collecting and card development. Players are merchants of the Renaissance trying to buy gem mines, means of transportation, shops; all in order to acquire the most prestige points. If you're wealthy enough, you might even receive a visit from a noble at some point, which of course will further increase your prestige.On your turn, you may (1) collect chips (gems), or (2) buy and build a card, or (3) reserve one card. If you collect chips, you take either three different kinds of chips or two chips of the same kind. If you buy a card, you pay its price in chips and add it to your playing area. To reserve a card, you place it in front of you face down for later building; this costs you a round, but you also get gold in the form of a joker chip, which you can use as any gem.All of the cards you buy increase your wealth as they give you a permanent gem bonus for later buys; some of the cards also give you prestige points. In order to win the game, you must reach 15 prestige points before your opponents do.",
"genre": "Card Game",
"rating": 3.465399437888002,
"rank": 17,
"board_score": -1,
"card_score": 1,
"party_score": -5,
"players_score": 3
},
{
"id": 18,
"name": "Ticket To Ride",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254202421-61wLscAHHSL.jpg",
"price": 59.99,
"max_players": 5,
"min_players": 2,
"play_time": 45,
"description": "Ticket to Ride is a cross-country train adventure game. Players collect train cards that enable them to claim railway routes connecting cities throughout North America. The longer the routes, the more points they earn. Additional points come to those who can fulfill their Destination Tickets by connecting two distant cities, and to the player who builds the longest continuous railway. So climb aboard for some railroading fun and adventure. You've got a Ticket to Ride! October 2, 1900 -- it's 28 years to the day that noted London eccentric, Phileas Fogg accepted and then won a 20,000 bet that he could travel Around the World in 80 Days. Now at the dawn of the century some old friends have gathered to celebrate Fogg's impetuous and lucrative gamble -- and to propose a new wager of their own. The stakes: $1 million in a winner-takes-all competition. The objective: to see the most cities in North America -- in just 7 days.  -Spiel Des Jahres 2004(German game of the year) -As d'Or Cannes 2004 (French game of the year) -Game of the year 2004 - Japan -Game of the year 2004 - Sweden -Game of the year 2004 - Finland -Diana Jones Excellence in Gaming Award 2004 -Origins Award Winner - Best Board Game 2005 -Game of the year 2004 - Spain -Parent's Choice Foundation Silver Medal 2004",
"genre": "Econonmic",
"rating": 3.4470322342946047,
"rank": 18,
"board_score": 8,
"card_score": 1,
"party_score": -9,
"players_score": 5
},
{
"id": 19,
"name": "Race for the Galaxy",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200326-516WSoozIAL.jpg",
"price": 18,
"max_players": 4,
"min_players": 2,
"play_time": 30,
"description": "In Race for the Galaxy from Rio Grande Games, players build galactic civilizations using game cards that represent worlds or technical and social developments. Each round consists of one or more of five possible phases. In each round, each player secretly and simultaneously chooses one of seven different action cards and then reveals it. Only the selected phases occur. For these phases, every player performs the phasea€s action, while the selecting player(s) also get a bonus for that phase. For example, if at least one player chooses the Develop action, then the Develop phase will occur, otherwise it is skipped. In it, each player may simultaneously select a development from his hand of cards to build. After revealing the cards, each player adds his development to his tableau of cards on the table and then discards cards from his hand equal to its cost. Each player who chose Develop discards one card fewer as his bonus. Explore allows a player to draw cards and select which of them to add to his hand. Settle allows a player to place a world in his tableau. Some worlds produce goods, represented by face down cards, when Produce is selected. These goods can be discarded for victory points or sold to add cards to the player's hand by selecting Consume. With cards, players can settle new worlds and build more developments, gaining both victory points and card powers that provide advantages in certain phases. The player who best manages his cards, phase and bonus selections, and card powers to build the greatest space empire, wins. The winner is the player with the most victory points.",
"genre": "Sci-Fi",
"rating": 3.737629034496344,
"rank": 19,
"board_score": -1,
"card_score": 1,
"party_score": 9,
"players_score": 3
},
{
"id": 20,
"name": "Santorini",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254194904-61JlvFn9fqL.jpg",
"price": 14.33,
"max_players": 4,
"min_players": 2,
"play_time": 15,
"description": "Welcome to the world of Santorini, a fantastic reimagining of the classic abstract game from 2004. Players are given a sandbox in which to play as gods, moving their workers around the board to build up a beautiful, multi-tiered city. Do you have what it takes to outsmart your opponents? Find out, in Santorini!Build it Up! Turns in Santorini are made up of two simple step: Move and Build. Move around the board and build a building in a spot adjacent to one of your workers. The first player to move their worker from a second level building to a third level building wins the game! Though, there are a few things that add a wrinkle to the basic formula.Invoke the Power of the gods!Each player will have access to a god power which lets them do things a little differently than normal. Be it changing the rules for how you can build or move, changing how you interact with other players, or providing you with an alternate victory condition, the 30 different god powers are sure to make every game of Santorini different and exciting! ",
"genre": "Fantasy",
"rating": 3.6283692266016514,
"rank": 20,
"board_score": 5,
"card_score": 1,
"card_score": 1,
"party_score": 6,
"players_score": 2
},
{
"id": 21,
"name": "Patchwork",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254997949-61iejxLClRL.jpg",
"price": 15.99,
"max_players": 2,
"min_players": 2,
"play_time": 15,
"description": "Patchwork is a form of needlework that involves sewing together pieces of fabric into a larger design. In the past, it was a way to make use of leftover pieces of cloth to create clothing and quilts. Today, patchwork is a form of art, in which the designers use precious fabrics to create beautiful textiles. The use of uneven pieces of fabric in particular can result in real masterpieces and is therefore being practiced by a large number of textile artists. To create a beautiful quilt, however, requires effort and time, but the available patches just do not want to fit together. So choose your patches carefully and keep a healthy supply of buttons to not only finish your quilt, but to make it better and more beautiful than your opponent's.",
"genre": "Puzzle",
"rating": 3.5963572934491763,
"rank": 21,
"board_score": 7,
"card_score": 1,
"party_score": -5,
"players_score": 2
},
{
"id": 22,
"name": "Brass: Birmingham",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254167105-512dvhVT-iL.jpg",
"price": 69.95,
"max_players": 4,
"min_players": 2,
"play_time": 120,
"description": "Brass: Birmingham is an economic strategy game sequel to Martin Wallace' 2007 masterpiece, Brass. Birmingham tells the story of competing entrepreneurs in Birmingham during the industrial revolution, between the years of 1770-1870. As in its predecessor, you must develop, build, and establish your industries and network, in an effort to exploit low or high market demands.",
"genre": "Economic",
"rating": 4.215686274509808,
"rank": 22,
"board_score": 8,
"card_score": 1,
"party_score": -8,
"players_score": 4
},
{
"id": 23,
"name": "Catan",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
"price": 24.69,
"max_players": 4,
"min_players": 3,
"play_time": 45,
"description": "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!",
"genre": "Economic",
"rating": 3.1374475480100656,
"rank": 23,
"board_score": 7,
"card_score": 1,
"party_score": -2,
"players_score": 4
},
{
"id": 24,
"name": "Everdell",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254898769-61I1Qnnt-UL.jpg",
"price": 60,
"max_players": 4,
"min_players": 1,
"play_time": 60,
"description": "Within the charming valley of Everdell, beneath the boughs of towering trees, among meandering streams and mossy hollows, a civilization of forest critters is thriving and expanding. From Everfrost to Bellsong, many a year have come and gone, but the time has come for new territories to be settled and new cities established. You will be the leader of a group of critters intent on just such a task. There are buildings to construct, lively characters to meet, events to host - you have a busy year ahead of yourself. Will the sun shine brightest on your city before the winter moon rises?  Everdell is a game of dynamic tableau building and worker placement. On their turn a player can take one of three actions: a) Place a Worker: Each player has a collection of Worker pieces. These are placed on the board locations, events, and on Destination cards. Workers perform various actions to further the development of a player's tableau: gathering resources, drawing cards, and taking other special actions. b) Play a Card: Each player is building and populating a city; a tableau of up to 15 Construction and Critter cards. There are five types of cards: Travelers, Production, Destination, Governance, and Prosperity. Cards generate resources (twigs, resin, pebbles, and berries), grant abilities, and ultimately score points. The interactions of the cards reveal numerous strategies and a near infinite variety of working cities. c) Prepare for the next Season: Workers are returned to the players supply and new workers are added. The game is played from Winter through to the onset of the following winter, at which point the player with the city with the most points wins.",
"genre": "Card Game",
"rating": 3.8521126760563384,
"rank": 24,
"board_score": -1,
"card_score": 1,
"party_score": 8,
"players_score": 3
},
{
"id": 25,
"name": "Jaipur",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1600812945534",
"price": 21.29,
"max_players": 2,
"min_players": 2,
"play_time": 30,
"description": "Jaipur, capital of Rajasthan. You are one of the two most powerful traders in the city.But that's not enough for you, because only the merchant with two Seals of Excellence will have the privilege of being invited to the Maharaja's court.You are therefore going to have to do better than your direct competitor by buying, exchanging and selling at better prices, all while keeping an eye on both your camel herds.A card game for two seasoned traders!",
"genre": "Card Game",
"rating": 3.585276414156388,
"rank": 25,
"board_score": 1,
"card_score": 9,
"party_score": 3,
"players_score": 2
},
{
"id": 26,
"name": "Great Western Trail",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200326-51nQKg6k7DL.jpg",
"price": 99.99,
"max_players": 4,
"min_players": 2,
"play_time": 75,
"description": "This ain't your average, everyday Euro game! Welcome to the Great Western Trail, where players take on the role of cattle drivers attempting to wrangle their herd to market. The trail will be tough, and countless hazards await you. Can you make it to the end of your journey and turn a tidy profit? Find out in Great Western Trail!Simple Mechanics, Complex DecisionsTurns in Great Western Trail are broken into three simple phases that will carry you through the entire game. These simple phases belie a web of deep and complex decisions players will face as they make their way down the trail. The mechanics are simple, but mastering the trail is where the fun lies.Make Your Move!A turn starts by moving your cattleman down the trail. The number of spaces a player is allowed to move is dictated by their player board, and there are hazards a plenty all along the trail. Wherever you end up, the next phase is ...Take Action!When a player ends their movement, they perform the action listed on the space they ended on. Depending on where you land, you will have different options available to you. Neutral locations or buildings you own will allow you to perform a special action specific to that location or a single auxiliary action. On locations owned by other players, hazard tiles, or teepee tiles, your only option is to use an auxiliary action. Last, there's Kansas City!Kansas City or Bust!Landing on Kansas City sets off a series of subphases that must be resolved in order: Three Foresight phases, the Income Phase, and the Delivery Phase. The Foresight subphases give players a choice between two tiles to add to the board (hazard, teepee, or worker). These tiles will affect future trips down the trail, so choose wisely. Earn income from your journey down the trail by revealing and discarding your hand. Finally, choose a city to deliver your cattle to. This leg of your journey is over. Now it's time to do it all again!Draw!Draw up to your hand limit and your turn is over! Time to start planning your next move and figure out the choices you'll face in the coming turns.",
"genre": "Strategy",
"rating": 3.9747437798648875,
"rank": 26,
"board_score": 8,
"card_score": 1,
"party_score": 0,
"players_score": 4
},
{
"id": 27,
"name": "Kingdomino",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254188772-515tbFJ5C8L.jpg",
"price": 13.99,
"max_players": 4,
"min_players": 2,
"play_time": 15,
"description": " Kingdomino is a 2-4 player strategy game that plays like dominoes with a kingdom-building twist. Each turn you will connect a new domino to your existing kingdom, making sure that at least one of its sides connects to a matching element already in play.Make sure to include dominoes with crowns on them, because at the end of the game you will score points equal to the total number of matching elements multiplied by the number of crowns.",
"genre": "Territory Building",
"rating": 3.4732316166664594,
"rank": 27,
"board_score": 4,
"card_score": 1,
"party_score": 1,
"players_score": 4
},
{
"id": 68,
"name": "Takenoko",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1600813601409",
"price": 34.99,
"max_players": 4,
"min_players": 2,
"play_time": 45,
"description": "Players take the role of courtesans of the Nippon emperor. They take care of his Giant Panda by growing a bamboo plantation. Their mission: to farm parcels of land, irrigate them, and have green, yellow or pink bamboo grow. In turn, they see what the weather brings and perform two actions from among those offered to them: get a new plot of land or irrigation channel, grow bamboo, feed the panda or draw an objective card. The game ends when a player has completed 7 to 9 objectives (depending on the number of players). The player who gets the best score by adding the total value of their completed objective wins the game.  Awards: 2012 Golden Geek Winner - Best Art and Presentation",
"genre": "Territory Building",
"rating": 3.3422025129342225,
"rank": 68,
"board_score": -2,
"card_score": 1,
"party_score": 3,
"players_score": 3
},
{
"id": 28,
"name": "Love Letter",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1539298538869",
"price": 9.34,
"max_players": 4,
"min_players": 2,
"play_time": 20,
"description": "All of the eligible young men (and many of the not-so-young) seek to woo the princess of Tempest. Unfortunately, she has locked herself in the Palace, and you must rely on others to bring your romantic letters to her. Will yours reach her first? Love Letter is a game of risk, deduction, and luck for 2 to 4 players. Your goal is to get your love letter into Princess Annette's hands while deflecting the letters from competing suitors. From a deck with only sixteen cards, each player starts with only one card in hand; one card is removed from play. On a turn, you draw one card, and play one card, trying to expose others and knock them from the game. Powerful cards lead to early gains, but make you a target. Rely on weaker cards for too long, however, and your letter may be tossed in the fire.Munchkin Loot Letter:Steal the treasure and backstab your friends - without all of the silly card-playing stuff. Well, without some of it. OK, without all but 16 cards of it, at least. Munchkin Loot Letter is a game of risk, deduction, and luck for 2-4 players.Love Letter: Legend of the Five Rings:Love and Honor. A vision of loveliness and poise, Iweko Miaka’s position of princess in the Imperial family ensures her betrothal will be a great contest for the samurai clans of the Emerald Empire. Whichever clan can win her as a wife for one of their young samurai will secure standing and glory for decades to come. And though the marriage may be political, what better way to influence the decision than by winning the heart of the princess herself?Letters to Santa:If you want all of your Christmas wishes brought by the big guy, you’ll need to make sure your letter makes it to him. The closer you get the letter to Santa, the more likely you are to win! But watch out for the wily Krampus, out to dash your yuletide dreams!Letters to Santa is a game of risk, deduction, and luck for 2–4 players. Your goal is to get your letter into Santa's hands while deflecting the letters from others. From a deck with only sixteen cards, each player starts with only one card in hand; one card is removed from play. On a turn, you draw one card, and play one card, trying to expose others and knock them from the game. Powerful cards lead to early gains, but make you a target. Rely on weaker cards for too long, however, and your letter may be tossed in the fire!",
"genre": "Card Game",
"rating": 3.317871714369526,
"rank": 28,
"board_score": -4,
"card_score": 1,
"party_score": -8,
"players_score": 4
},
{
"id": 29,
"name": "Star Realms",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258032901-51VCCs9ppIL.jpg",
"price": 9.99,
"max_players": 2,
"min_players": 2,
"play_time": 15,
"description": " Star Realms is a spaceship combat deck building game designed by Magic Pro Tour Champions and Hall of Famers Darwin Kastle and Rob Dougherty (developer and cofounder of the Ascension Deck building Game). Star Realms offers all the thrills of traditional trading card game style combat, combined with the fun of a deck building game. Play powerful ships, destroy enemy bases or blast your opponent directly on your way to victory!  CONTENTS: 128 beautifully illustrated cards: 80 card main deck, 10 Explorer cards, Two 10 card personal decks, 18 double-sided score cards And two full-color rule sheet.",
"genre": "Sci-Fi",
"rating": 3.4965487417528696,
"rank": 29,
"board_score": -2,
"card_score": 1,
"party_score": 8,
"players_score": 2
},
{
"id": 30,
"name": "King of Tokyo",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257600208-61doPBeJTjL.jpg",
"price": 31.43,
"max_players": 6,
"min_players": 2,
"play_time": 30,
"description": "This new edition of the best-seller boasts new artwork, clearer rules, and revamped card abilities. Monsters have a new look, and the coveted space penguin character takes his place in Tokyo! King of Tokyo is a game for 2 to 6 players where you play as Mutant monsters, rampaging robots, or even abominable aliens battling in a fun, chaotic atmosphere.  Roll dice and choose your strategy: will you attack your enemies? Heal your wounds? improve your monster? Stomp your path to victory.",
"genre": "Fantasy",
"rating": 3.2163033611828467,
"rank": 30,
"board_score": -5,
"card_score": 1,
"party_score": 8,
"players_score": 6
},
{
"id": 31,
"name": "Lords of Waterdeep",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1538677407703",
"price": 27,
"max_players": 5,
"min_players": 2,
"play_time": 60,
"description": "Waterdeep, the City of Splendors--the most resplendent jewel in the Forgotten Realms, and a den of political intrigue and shady back-alley dealings. In this game, the players are powerful lords vying for control of this great city. Its treasures and resources are ripe for the taking, and that which cannot be gained through trickery and negotiation must be taken by force!Lords of Waterdeep is a Euro-style board game for 2-5 players.Components: Game board Rulebook 5 card stock player mats 121 Intrigue, Quest, and Role cards 130 wooden cubes, pawns, and score pieces Wooden player markers Card stock tiles and tokens representing buildings, gold coins, and victory points",
"genre": "Fantasy",
"rating": 3.5488917575957553,
"rank": 31,
"board_score": 5,
"card_score": 1,
"party_score": 5,
"players_score": 5
},
{
"id": 32,
"name": "Architects of the West Kingdom",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1540939581145",
"price": 34.95,
"max_players": 5,
"min_players": 1,
"play_time": 60,
"description": "Architects of the West Kingdom is set at the end of the Carolingian Empire, circa 850 AD. As royal architects, players compete to impress their King and maintain their noble status by constructing various landmarks throughout his newly appointed domain. Players will need to collect raw materials, hire apprentices and keep a watchful eye on their workforce. These are treacherous times. Rival architects will stop at nothing to slow your progress. Will you remain virtuous, or be found in the company of thieves and black marketeers?The aim of Architects of the West Kingdom is to be the player with the most Victory Points (VP) at the game's end. Points are gained by constructing various Buildings and advancing work on the Archbishop's Cathedral. Throughout the game, players will need to make a lot of moral decisions. However, only at the game's end will their virtue be judged. A few underhanded deals here and there might not seem like much, but fall too far and you will be punished. The game ends once a set number of constructions have been completed.",
"genre": "Building",
"rating": 3.8388888888888895,
"rank": 32,
"board_score": 5,
"card_score": 1,
"party_score": 2,
"players_score": 4
},
{
"id": 33,
"name": "Welcome to...",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1538760984196",
"price": 17.5,
"max_players": 100,
"min_players": 1,
"play_time": 25,
"description": "A roll and write without dice! Players will become architects in the American 50's as they use combinations of cards and actions to construct American dream real estate. As an architect in Welcome to, you want to build the best new town in the United States during the 1950s. Players are developing estates, parks, pools, hiring employees, and more. Welcome to plays like a roll-and-write dice game in which you mark results on a scoresheet... but without dice.",
"genre": "Building",
"rating": 3.7172300807160563,
"rank": 33,
"board_score": 5,
"card_score": 1,
"party_score": -8,
"players_score": 10
},
{
"id": 34,
"name": "The Quacks of Quedlinburg",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1599058217796",
"price": 54.99,
"max_players": 4,
"min_players": 2,
"play_time": 60,
"description": "Toadstools, Mandrake, and African Death's Head Hawksmoth, Oh My! It is the 9-day Quedlinburg festival of quack doctors. Purchasing good ingredients for your brew can help you make the best &quot;healing&quot; ointments in the land, winning you fame and fortune! You can use that fortune to buy even more powerful ingredients to put into your pot. But be careful, one ingredient too many and your potion will explode! Winner of the 2018 Kennerspiel des Jahres, The Quacks of Quedlinburg perfectly blends deck, i.e. 'pot', building strategy with a press your luck element that ratchets up the excitement each turn as the stakes get higher.",
"genre": "Strategy",
"rating": 3.877168109536333,
"rank": 34,
"board_score": 6,
"card_score": 1,
"party_score": 4,
"players_score": 4
},
{
"id": 35,
"name": "Clans of Caledonia",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1604080716475",
"price": 49.99,
"max_players": 4,
"min_players": 1,
"play_time": 30,
"description": "Clans of Caledonia is a mid-to-heavy economic game set in 19th-century Scotland. At this time, Scotland made the transition from an agricultural to an industrialized country that heavily relied on trade and export. In the following years, food production increased significantly to feed the population growth. Linen was increasingly substituted by the cheaper cotton and raising sheep was given high importance. More and more distilleries were founded and whisky became the premium alcoholic beverage in Europe. Players represent historic clans with unique abilities and compete to produce, trade and export agricultural goods and of course whisky! The game comes with nine different clans, a modular board with 16 configurations, nine port bonuses and nine round scoring tiles.",
"genre": "Economic",
"rating": 3.9378309409888375,
"rank": 35,
"board_score": 7,
"card_score": 1,
"party_score": -5,
"players_score": 4
},
{
"id": 37,
"name": "Blood Rage",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254863709-51lrsCB5VWL.jpg",
"price": 72.95,
"max_players": 4,
"min_players": 2,
"play_time": 60,
"description": "In Blood Rage, each player controls their own Viking clan's warriors, leader, and ship. Ragnarok has come, and it's the end of the world! It's the Vikings' last chance to go down in a blaze of glory and secure their place in Valhalla at Odin's side! For a Viking there are many pathways to glory. You can invade and pillage the land for its rewards, crush your opponents in epic battles, fulfil quests, increase your clan's stats, or even die gloriously either in battle or from Ragnarok, the ultimate inescapable doom. Most player strategies are guided by the cards drafted at the beginning of each of the three game rounds (or Ages). These &quot;Gods' Gifts&quot; grant you numerous boons for your clan including: increased Viking strength and devious battle strategies, upgrades to your clan, or even the aid of legendary creatures from Norse mythology. They may also include various quests, from dominating specific provinces, to having lots of your Vikings sent to Valhalla. Most of these cards are aligned with one of the Norse gods, hinting at the kind of strategy they support. For example, Thor gives more glory for victory in battle, Heimdall grants you foresight and surprises, Tyr strengthens you in battle, while the trickster Loki actually rewards you for losing battles, or punishes the winner. Players must choose their strategies carefully during the draft phase, but also be ready to adapt and react to their opponents' strategies as the action phase unfolds. Battles are decided not only by the strength of the figures involved, but also by cards played in secret. By observing your opponents' actions and allegiances to specific gods, you may predict what card they are likely to play, and plan accordingly. Winning battles is not always the best course of action, as the right card can get you even more rewards by being crushed. The only losing strategy in Blood Rage is to shy away from battle and a glorious death!",
"genre": "Fantasy",
"rating": 3.698714202220923,
"rank": 37,
"board_score": 8,
"card_score": 1,
"party_score": 9,
"players_score": 4
},
{
"id": 38,
"name": "Small World",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254992240-511JJsfrrNL.jpg",
"price": 37.99,
"max_players": 5,
"min_players": 2,
"play_time": 40,
"description": " Small World is designed by Philippe Keyaerts and is a fantasy-themed game similar in game play to his Vinci, which was released in 1999 by French publisher Descartes. In Small World, players will be able to control characters from 14 fantasy races - dwarves, giants, orcs, elves, and so forth - while trying to take control of territory and push opponents out of adjacent lands and off the map. Even while dominating opponents, however, you have to keep in mind that your race's civilization is doomed as well, thanks to the passing of time and attacking of neighbors, so be ready to cast aside one tribe while taking the reins of another in order to keep dominating the world.Small World is for 2-5 players and contains two double-sided gameboards, with one side being used for each of the different number of possible players. The 14 fantasy races come with matching banners and tokens, and the game also includes 20 special power badges to further customize the races along with mountains, troll lairs, fortresses, holes-in-the-ground, victory coins. and other items.",
"genre": "Fantasy",
"rating": 3.3195257356896004,
"rank": 38,
"board_score": 6,
"card_score": 1,
"party_score": 10,
"players_score": 5
},
{
"id": 39,
"name": "Puerto Rico",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559255812091-51jb0LuMmEL.jpg",
"price": 15.3,
"max_players": 5,
"min_players": 2,
"play_time": 90,
"description": "Prospector, captain, mayor, trader, settler, craftsman, or builder? Which roles will you play in the new world? Will you own the most prosperous plantations? Will you build the most valuable buildings? You have but one goal: achieve the greatest prosperity and highest respect! This is shown by the player who earns the most victory points. He will win the game!",
"genre": "Building",
"rating": 3.6584374999999993,
"rank": 39,
"board_score": 2,
"card_score": 1,
"party_score": -10,
"players_score": 5
},
{
"id": 40,
"name": "Dead of Winter: A Crossroads Game",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1574700781988",
"price": 43.96,
"max_players": 5,
"min_players": 2,
"play_time": 45,
"description": "Dead of Winter puts 2-5 players together in a small, weakened colony of survivors in a world where most of humanity are either dead or diseased, flesh-craving monsters. Each player leads a faction of survivors with dozens of different characters in the game. Dead of Winter is a meta-cooperative psychological survival game. This means players are working together toward one common victory condition--but for each individual player to achieve victory, they must also complete their personal secret objective. This secret objective could relate to a psychological tick that's fairly harmless to most others in the colony, a dangerous obsession that could put the main objective at risk, a desire for sabotage of the main mission, or worst of all: vengeance against the colony! Certain games could end with all players winning, some winning and some losing, or all players losing. Work toward the group's goal but don't get walked all over by a loudmouth who's only looking out for their own interests!",
"genre": "Party",
"rating": 3.5335323243169534,
"rank": 40,
"board_score": -9,
"card_score": 1,
"party_score": 8,
"players_score": 5
},
{
"id": 41,
"name": "Forbidden Island",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1539384798707",
"price": 8.1,
"max_players": 4,
"min_players": 2,
"play_time": 30,
"description": "Dare to discover  Forbidden Island! Join a team of fearless adventurers on a do-or-die mission to capture four sacred treasures from the ruins of this perilous paradise. Your team will have to work together and make some pulse-pounding maneuvers, as the island will sink beneath every step! Race to collect the treasures and make a triumphant escape before you are swallowed into the watery abyss! Nominated for the 2011 Spiel des Jahres (Game of the Year) Award.",
"genre": "Econonmic",
"rating": 3.197969543147205,
"rank": 41,
"board_score": 4,
"card_score": 1,
"party_score": 6,
"players_score": 4
},
{
"id": 42,
"name": "Dominion: Second Edition",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254994298-61H6ZZGTpdL.jpg",
"price": 30.49,
"max_players": 4,
"min_players": 2,
"play_time": 15,
"description": "You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion!  In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner. Rio Grande Games has updated Dominion in this Second Edition. New cover and replaced a few cards; cleaned up rules and card text. Artwork on the Base cards have been changed to be similar to that found previously in Base Cards.",
"genre": "Strategy",
"rating": 3.4924219195269814,
"rank": 42,
"board_score": -1,
"card_score": 1,
"party_score": -4,
"players_score": 3
},
{
"id": 43,
"name": "Five Tribes",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254126853-611YVb5GCwL.jpg",
"price": 47.99,
"max_players": 4,
"min_players": 2,
"play_time": 60,
"description": "Crossing into the Land of 1001 Nights, your caravan arrives at the fabled Sultanate of Naqala. The old sultan just died and control of Naqala is up for grabs! The oracles foretold of strangers who would maneuver the Five Tribes to gain influence over the legendary city-state. Will you fulfill the prophecy? Invoke the old Djinns, move the Tribes into position at the right time and the Sultanate may become yours!",
"genre": "Fantasy",
"rating": 3.725187769736575,
"rank": 43,
"board_score": 8,
"card_score": 1,
"party_score": 5,
"players_score": 3
},
{
"id": 69,
"name": "Stone Age",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254167104-512BzBFksXNL.jpg",
"price": 37.5,
"max_players": 5,
"min_players": 2,
"play_time": 60,
"description": "Your family is fed. You have a roof over your head. You've succeed in building a civilization that will prosper for eternity. But have you seen the latest fashion? - Use jewelry to buy powerful new buildings and stock up on Civilization cards. - Improve the value of your jewelry and resources with this new actions.",
"genre": "Economic",
"rating": 3.4733595800524952,
"rank": 69,
"board_score": 4,
"card_score": 1,
"party_score": -3,
"players_score": 4
},
{
"id": 70,
"name": "Sheriff of Nottingham",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254204253-61te4F7OK2BL.jpg",
"price": 95,
"max_players": 5,
"min_players": 3,
"play_time": 60,
"description": "The Sheriff of Nottingham is a fun and engaging game for all where each player will have the chance to be the Sheriff himself! As peasants, players will declare goods they wish to bring into the city and it will be up to the Sheriff to decide who is telling the truth and who is secretly trying to smuggle in contraband! Experience Nottingham in a whole new way! Declare your goods, deal with the Sheriff and secure victory in a fun-filled and exciting adventure! ",
"genre": "Party",
"rating": 3.213004788826288,
"rank": 70,
"board_score": -9,
"card_score": 1,
"party_score": -3,
"players_score": 5
},
{
"id": 44,
"name": "Arkham Horror: The Card Game",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257204681-515mUPxEHZL.jpg",
"price": 35.42,
"max_players": 2,
"min_players": 1,
"play_time": 60,
"description": "Something evil stirs in Arkham, and only you can stop it. Blurring the traditional lines between roleplaying and card game experiences,  Arkham Horror: The Card Game is the living card game of love craft I an mystery, monsters, and madness! You and your friend (or up to three friends with two core sets) become characters within the quiet new England town of Arkham. You have your talents, sure, but you also have your flaws. Perhaps you've dabbled a little too much in the writings of the Necronomicon, and its words continue to haunt you. Perhaps you feel compelled to cover up any signs of otherworldly evils, hampering your own investigations in order to protect the quiet confidence of the greater population. Perhaps you'll be scarred by your encounters with a ghoulish cult. No matter what compels you, no matter what haunts you, you'll find both your strengths and weaknesses reflected in your custom deck of cards, and these cards will be your resources as you work with your friends to unravel the world's most terrifying mysteries. Meanwhile, each of your adventures in Arkham Horror: The Card Game carries you deeper into mystery. You'll find cultists and foul rituals. You'll find haunted houses and strange creatures. And you may find signs of the ancient ones straining against the barriers to our world… the basic mode of play in Arkham Horror: The Card Game is not the adventure, but the campaign. You might be scarred by your adventures, your sanity may be strained, and you may alter Arkham's landscape, burning buildings to the ground. All your choices and actions have consequences that reach far beyond the immediate resolution of the scenario at hand. And your actions may earn you valuable experience with which you can better prepare yourself for the adventures that still lie before you.",
"genre": "Card Game",
"rating": 3.8802407638024072,
"rank": 44,
"board_score": -1,
"card_score": 1,
"party_score": 6,
"players_score": 2
},
{
"id": 45,
"name": "Sagrada",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254943589-61wqSdWtkHL.jpg",
"price": 27.97,
"max_players": 4,
"min_players": 1,
"play_time": 20,
"description": "As a skilled artisan, use tools-of-the-trade and careful planning to construct a stained glass window masterpiece in the Sagrada Familia. Gain prestige by adapting to the preferences of your fickle admirers, and, of course, by adding your own artistic flair while completing your glass masterpiece in Sagrada, a game of dice-drafting and window-crafting.",
"genre": "Puzzle",
"rating": 3.5611319035621776,
"rank": 45,
"board_score": -5,
"card_score": 1,
"party_score": -5,
"players_score": 3
},
{
"id": 46,
"name": "Tzolk'in: The Mayan Calendar",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-61f2BdYqPR4L.jpg",
"price": 41.99,
"max_players": 4,
"min_players": 2,
"play_time": 60,
"description": "The Maya were a highly developed civilization known for its unique art, complex architecture, sophisticated mathematics and advanced knowledge of the stars. At the heart of their society was a mysterious calendar - Tzolk'in. With a length of 260 days, it could predict the right time to plant seeds, the time to build monuments, the day a new baby would be born as well as the movement of the planets. It was the centerpiece of the Mayan cycle of life. We invite you to become one of the ajaw, the leaders of Mayan tribes. Please the gods and lead your clan to prosperity! As in the life of ancient Maya, the center of our game is the Tzolk'in calendar - a set of gears that rotate each round of the game. This unique system helps you to visualize the cyclic flow of time and plan your actions in advance. Harvest crops now, or wait for them to grow a little more for higher yield? All will be clear to see on the wheels of time.",
"genre": "Economic",
"rating": 3.721545859123228,
"rank": 46,
"board_score": 6,
"card_score": 1,
"party_score": -3,
"players_score": 4
},
{
"id": 47,
"name": "Orléans",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257869368-51gGAV82BOAL.jpg",
"price": 39.99,
"max_players": 4,
"min_players": 2,
"play_time": 90,
"description": "Grow your economic reach and gather followers in this bag-building game. A game for 2 to 4 players. In medieval Orleans, you will gather followers, establish trade stations, and collect goods and money to gain supremacy. This is a bag building game with many paths to victory and huge replay ability.",
"genre": "Strategy",
"rating": 3.904217648488775,
"rank": 47,
"board_score": 4,
"card_score": 1,
"party_score": -3,
"players_score": 4
},
{
"id": 48,
"name": "Sushi Go!",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254990668-51CIdEFrKKL.jpg",
"price": 8.02,
"max_players": 5,
"min_players": 2,
"play_time": 15,
"description": "In this fast-playing card game, the goal is to grab the best combination of sushi dishes as they whiz by. Score points for making the most maki rolls or for collecting a full set of sashimi. Dip your favorite nigiri in wasabi to triple its value! But be sure to leave room for dessert or else you'll eat into your score! Gather the most points and consider yourself the sushi master!",
"genre": "Card Game",
"rating": 3.2819423596186703,
"rank": 48,
"board_score": -4,
"card_score": 1,
"party_score": -7,
"players_score": 5
},
{
"id": 49,
"name": "Lost Cities",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1560987947482",
"price": 12.6,
"max_players": 2,
"min_players": 2,
"play_time": 30,
"description": "Who will discover the ancient civilizations?Two explorers embark on research journeys to remote corners of the world: the Himalayan mountains, the Central American rainforest, the Egyptian desert, a mysterious volcano, and the bottom of the sea. As the cards are played, the expedition routes take shape and the explorers earn points. The most daring adventurers make bets on the success of their expeditions. The explorer with the highest score after three rounds of expeditions wins. The rules of the game are simple, but beware: The lost cities hold many unseen mysteries!",
"genre": "Card Game",
"rating": 3.4199999999999986,
"rank": 49,
"board_score": -2,
"card_score": 1,
"party_score": -5,
"players_score": 2
},
{
"id": 50,
"name": "Roll For The Galaxy",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254202422-61MFI-RHExL.jpg",
"price": 36,
"max_players": 5,
"min_players": 2,
"play_time": 45,
"description": "Roll for the Galaxy is a dice game of building space empires for 2-5 players. Your dice represent your populace, whom you direct to develop new technologies, settle worlds, and ship goods. The player who best manages his workers and builds the most prosperous empire wins! This dice version of Race for the Galaxy takes players on a new journey through the Galaxy, but with the the feel of the original game.",
"genre": "Strategy",
"rating": 3.6683159498417908,
"rank": 50,
"board_score": 1,
"card_score": 1,
"party_score": 9,
"players_score": 3
},
{
"id": 51,
"name": "Ticket to Ride: Europe",
"image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183527-61HYBjXXnEL.jpg",
"price": 24.74,
"max_players": 5,
"min_players": 2,
"play_time": 30,
"description": "Ticket to Ride: Europe takes you on a new train adventure across Europe. From Edinburgh to Constantinople and from Lisbon to Moscow, you'll visit great cities of turn-of-the-century Europe. Like the original Ticket to Ride, the game remains elegantly simple, can be learned in 5 minutes, and appeals to both families and experienced gamers. Ticket to Ride: Europe is a complete and does not require the original version. More than just a new map, Ticket to Ride: Europe features brand new gameplay elements. Tunnels may require you to pay extra cards to build on them, Ferries require locomotive cards in order to claim them, and Stations allow you to sacrifice a few points in order to use an opponents route to connect yours.  The game also includes larger format cards and Train Station game pieces. The overall goal remains the same, collect and play train cards in order to place your pieces on the board, attempting to connect cities on your ticket cards. Points are earned both from placing trains and completing tickets but uncompleted tickets lose you points. The player who has the most points at the end of the game wins.-International Gamers Award 2005",
"genre": "Fantasy",
"rating": 3.5207909120934455,
"rank": 51,
"board_score": 8,
"card_score": 1,
"party_score": -9,
"players_score": 5
}
]
end
